---
bases:
  - "../../bases/helmDefaults.yaml"
  - "../../bases/environments.yaml"

---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: keycloak
    namespace: sixsense-dev
    chart: bitnami/keycloak
    version: 5.1.2
    labels:
      tier: infra
      domain: trasier
    values:
      - keycloak.values.yaml.gotmpl

  - name: trasier-server
    namespace: sixsense-dev
    chart: ../../../packages/trasier-server/.helm
    version: 0.0.1
    labels:
      tier: app
      domain: trasier
    needs:
      - sixsense-dev/keycloak
    values:
      - trasier.values.yaml.gotmpl