bases:
  - "helmfile/bases/helmDefaults.yaml"
  - "helmfile/bases/environments.yaml"

helmfiles:
  - "helmfile/releases/00-pact/helmfile.yaml"
  - "helmfile/releases/10-trasier/helmfile.yaml"
  - "helmfile/releases/11-hypertrace/helmfile.yaml"
  - "helmfile/releases/20-trasier-example/helmfile.yaml"
missingFileHandler: Error
