image:
  repository: tomassatka/trasier-server
  pullPolicy: Always
  tag: 0.0.1

replicaCount: 1
resources: {}
env:
  JAVA_OPTS: -Dmicronaut.config.files=/application.yaml

service:
  name: trasier
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080

ingress:
  enabled: false
