image:
  repository: docker.io/trasier/trasier-server
  pullPolicy: IfNotPresent
  tag: latest

replicaCount: 1
resources: {}
env:
  JAVA_OPTS: -Dmicronaut.config.files=/application.yaml

service:
  name: trasier
  type: ClusterIP
  externalPort: 8000
  internalPort: 8000

ingress:
  enabled: false
