apiVersion: builtin
kind: PatchTransformer
metadata:
  name: kafka
target:
  kind: StatefulSet
  name: kafka
patch: |-
  apiVersion: apps/v1
  kind: StatefulSet
  spec:
    template:
      spec:
        containers:
        - name: kafka
          volumeMounts:
          - mountPath: /opt/kafka/logs
            name: kafka-logs
        volumes:
        - name: kafka-logs
          emptyDir: {}