apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}
data:
  config.json: |
    {
      "env": "dev",
      "production": false,
      "mock": false,
      "readerHttpsUrl": "http://trasier-ui-sixsense-dev.192.168.1.35.nip.io",
      "webBackendHttpsUrl": "http://trasier-ui-sixsense-dev.192.168.1.35.nip.io/"
    }

  nginx.conf: |
    #user www-data;
    worker_processes  1;

    #error_log  logs/error.log;
    #pid   /run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include /etc/nginx/mime.types;

        gzip  on;
        gzip_http_version 1.1;
        gzip_comp_level 2;
        gzip_types text/plain text/html text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        server {
            listen 4200;
            location / {
                root /usr/share/nginx/html;
            }
            location /api {
                proxy_pass http://trasier:8000/api;
            }
        }
    }