---
helmDefaults:
#  atomic: true
  #TODO: deactivate
  atomic: false
  cleanupOnFail: false
#  wait: true
  #TODO: deactivate
  wait: false
  timeout: 5400
  # Do not recreate pods during upgrade when not required
  recreatePods: false
