---
bases:
  - "../../bases/helmDefaults.yaml"
  - "../../bases/environments.yaml"

---
releases:
  - name: apm-k6
    namespace: sixsense-dev
    chart: ../../../charts/k6
    version: 0.0.1
    labels:
      tier: app
      domain: apm-k6
    values:
      - apm-k6.values.yaml.gotmpl