apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}
data:
  application.yaml: |
    micronaut:
      application:
        name: trasier-server
      server:
        port: 8000
        cors:
          enabled: true
          configurations:
            allowedOrigins:
              - '*'

    trasier.elastic:
      namespace: {{ .Release.Namespace }}
      hosts:
        - {{ .Release.Name }}-elasticsearch-master
      port: 9200
      scheme: http
      index: default
      type: event
      cluster-name: default

