apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}
data:
  application.yaml: |
    server:
      port: 7001

    logging.level.com.trasier.client.spring.noop: TRACE

    offer:
      endpoint: {{ .Values.offer.endpoint }}

    trasier:
      endpoint:
        httpEndpoint: http://{{ .Values.trasier.endpoint }}/api/accounts/{{ .Values.trasier.accountId }}/spaces/{{ .Values.trasier.spaceKey }}/spans
      client:
        accountId: {{ .Values.trasier.accountId }}
        spaceKey: {{ .Values.trasier.spaceKey }}
        systemName: {{ .Values.trasier.systemName }}
        useAuth: false
